# appication.properties
# server.port=9090
# TODO: Dikkat, burada key-value çalışmalarında anahtar: bilgisinden sonra değer bir boşluk bırakılarak yazılmalıdır.
# YML yanlış kullanımları
# server:
#   port:9090  -- iki noktaya bitişik değer yazımı yanlıştır.
# server:
# port: 9090 -- port değeri server in alt başlığıdır bu nedenle aynı hizada değil bir tab içeride yazılmalı
server:
  port: 9090

# spring.datasource.url
# spring.datasource.username
# spring.datasource.password
# spring.datasource.driver-class-name

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/Java8PersonelYonetim"
    username: "postgres"
    password: "root"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: update # create-> her seferinden yeniden oluştur. create-drop-> uygulama kapatıldığında tabloları siler. update-> varsa günceller yoksa oluşturur.
    show-sql: true


